# -*- coding: utf-8 -*-

corners = [('Hutu', 'B3', 0, [(4, 3 * 7, 'backward'),
                              (5, 3 * 6 - 2, 'forward'),
                              (3, 3 * 7, 'backward')]),
           ('Debut', 'B2', 2000, [(4, 3 * 7, 'backward'),
                                  (5, 3 * 6 - 2, 'forward'),
                                  (3, 3 * 7, 'backward')]),
           ('HV', 'C3', 2500, [(4, 3 * 7, 'backward'),
                               (5, 3 * 6 - 2, 'forward'),
                               (3, 3 * 7, 'backward')]),
           ('Kei', 'A2', 3000, [(6 * 2, 3 * 3, 'split'),
                                (1, 5, 'backward'),
                                (6, 3 * 4, 'forward')]),
           ('KeiU25', 'A2', 3500, [(5, 3 * 3 + 5, 'backward')]),
           ('U25', 'C2', 4000, [(4, 3 * 7, 'backward'),
                                (5, 3 * 6 - 2, 'forward'),
                                (3, 3 * 7, 'backward')]),
           ('VT1', 'D', 62000, [(3, 2, 'backward'),
                                (1, 1, 'backward'),
                                (3, 10, 'backward'),
                                (1, 2, 'backward'),
                                (3, 5, 'backward'),
                                (5, 18 - 1, 'forward')]),
           ('VT2', 'D', 63500, [(5, 13, 'forward')]),
           ('MiniV', 'A3', 7000, [(1, 2, 'backward'),
                                  (6, 12, 'backward'),
                                  (4, 12 + 4 + 2, 'backward')]),
           ('Uri', 'B4', 9000, [(3, 3 * 7 + 1, 'backward'),
                                (5, 3 * 6 + 1 - 5, 'forward'),
                                (4, 3 * 7 + 1, 'backward')])]
